# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Push new game update and bump version

on:
  push:
    branches: [ master ]

jobs:
  version-bump:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        id: check_out_source_code
        uses: actions/checkout@v2

      - name: "Automated Version Bump"
        id: automated_version_bump
        uses: digza/automatic-python-version@0.0.13
        with:
          tag-prefix: ""
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
